version: "3.3"
volumes:
  jenkins-data: {}

services: 
  jenkins:
    image: jenkins/jenkins:lts
    deploy:
      replicas: 2
      resources:
        reservations:
          cpus: '2'
          memory: 2048M
      restart_policy:
         condition: on-failure
      placement:
        constraints: 
          - "node.role==worker"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

     
      